# Generated by Django 4.2.27 on 2025-12-15 09:26

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=50, unique=True, verbose_name='SKU')),
                ('name', models.CharField(max_length=100, verbose_name='名称')),
                ('unit', models.CharField(choices=[('PCS', '件'), ('BOX', '箱'), ('OTHER', '其他')], default='PCS', max_length=10, verbose_name='单位')),
                ('category', models.CharField(blank=True, max_length=50, verbose_name='分类（可选）')),
                ('barcode', models.CharField(blank=True, max_length=80, verbose_name='条码（可选）')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '物品',
                'verbose_name_plural': '物品',
                'ordering': ['sku'],
            },
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='仓库编码')),
                ('name', models.CharField(max_length=100, verbose_name='仓库名称')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '仓库',
                'verbose_name_plural': '仓库',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='StockMove',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('move_type', models.CharField(choices=[('INBOUND', '入库'), ('OUTBOUND', '出库'), ('ADJUST', '调整')], max_length=20, verbose_name='类型')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=12, verbose_name='数量')),
                ('unit_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='单位成本(可选)')),
                ('reference', models.CharField(blank=True, max_length=100, verbose_name='关联单号/来源(可选)')),
                ('note', models.TextField(blank=True, verbose_name='备注(可选)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='moves', to='products.item')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='moves', to='products.warehouse')),
            ],
            options={
                'verbose_name': '库存流水',
                'verbose_name_plural': '库存流水',
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['item', 'warehouse'], name='products_st_item_id_cf9889_idx'), models.Index(fields=['created_at'], name='products_st_created_81dbbe_idx')],
            },
        ),
        migrations.CreateModel(
            name='StockBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('on_hand', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=12, verbose_name='现存数量')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='balances', to='products.item')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='balances', to='products.warehouse')),
            ],
            options={
                'verbose_name': '库存余额',
                'verbose_name_plural': '库存余额',
                'indexes': [models.Index(fields=['item', 'warehouse'], name='products_st_item_id_ef2c5e_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='stockbalance',
            constraint=models.UniqueConstraint(fields=('item', 'warehouse'), name='uniq_balance_item_warehouse'),
        ),
    ]
