# Generated by Django 4.2.27 on 2025-12-15 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockbalance',
            name='on_hand',
            field=models.IntegerField(default=0, verbose_name='当前库存'),
        ),
        migrations.AlterField(
            model_name='stockmove',
            name='quantity',
            field=models.IntegerField(verbose_name='变动数量'),
        ),
    ]
