# Generated by Django 4.2.27 on 2026-01-02 08:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_stockbalance_on_hand_alter_stockmove_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='warehouse',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='items', to='products.warehouse', verbose_name='所属仓库'),
        ),
        migrations.AlterField(
            model_name='item',
            name='unit',
            field=models.CharField(choices=[('PCS', '件'), ('BOX', '箱'), ('OTHER', '其他')], default='PCS', max_length=20, verbose_name='单位'),
        ),
    ]
