# Generated by Django 4.2.27 on 2026-01-02 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_item_warehouse_alter_item_unit'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ['name'], 'verbose_name': '物品', 'verbose_name_plural': '物品'},
        ),
        migrations.AlterModelOptions(
            name='warehouse',
            options={'ordering': ['name'], 'verbose_name': '仓库', 'verbose_name_plural': '仓库'},
        ),
        migrations.RemoveField(
            model_name='item',
            name='sku',
        ),
        migrations.RemoveField(
            model_name='warehouse',
            name='code',
        ),
        migrations.AlterField(
            model_name='item',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='名称'),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='仓库名称'),
        ),
    ]
