# Generated by Django 4.2.27 on 2026-01-02 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_item_options_alter_warehouse_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='unit',
            field=models.CharField(choices=[('PCS', '件'), ('BOX', '箱'), ('GE', '个'), ('ZHI', '只'), ('OTHER', '其他')], default='PCS', max_length=20, verbose_name='单位'),
        ),
    ]
