# Generated by Django 4.2.27 on 2026-01-04 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_item_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='is_finished_good',
            field=models.BooleanField(default=False, verbose_name='是否为成品'),
        ),
    ]
