# Generated by Django 4.2.27 on 2026-01-09 07:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_item_is_finished_good'),
    ]

    operations = [
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='单位编码')),
                ('name', models.CharField(max_length=50, verbose_name='单位名称')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('sort_order', models.IntegerField(default=0, verbose_name='排序')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '单位',
                'verbose_name_plural': '单位',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.RemoveField(
            model_name='item',
            name='is_finished_good',
        ),
        migrations.RemoveField(
            model_name='item',
            name='warehouse',
        ),
        migrations.AddField(
            model_name='warehouse',
            name='warehouse_type',
            field=models.CharField(choices=[('RAW', '原材料仓'), ('FINISHED', '成品仓'), ('BOTH', '通用仓')], default='BOTH', max_length=20, verbose_name='仓库类型'),
        ),
        migrations.AlterField(
            model_name='item',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='products.unit', verbose_name='单位'),
        ),
    ]
