# Generated by Django 4.2.27 on 2026-01-09 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_unit_remove_item_is_finished_good_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='unit',
            options={'ordering': ['name'], 'verbose_name': '单位', 'verbose_name_plural': '单位'},
        ),
        migrations.RemoveField(
            model_name='unit',
            name='code',
        ),
        migrations.RemoveField(
            model_name='unit',
            name='sort_order',
        ),
    ]
