# Generated by Django 4.2.27 on 2026-01-09 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_alter_unit_options_remove_unit_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unit',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='单位名称'),
        ),
    ]
