# Generated by Django 4.2.27 on 2026-01-09 08:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_alter_unit_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='barcode',
        ),
        migrations.AddField(
            model_name='item',
            name='warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='items', to='products.warehouse', verbose_name='所属品类'),
        ),
    ]
