# Generated by Django 4.2.27 on 2026-02-02 02:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_partner_stockmove_partner'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='stockmove',
            new_name='products_st_partner_4ede59_idx',
            old_name='products_s_partner_5ba4fa_idx',
        ),
    ]
