# Generated by Django 4.2.27 on 2026-02-05 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_rename_products_s_partner_5ba4fa_idx_products_st_partner_4ede59_idx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockmove',
            name='move_type',
            field=models.CharField(choices=[('INBOUND', '入库'), ('OUTBOUND', '出库'), ('ADJUST', '调整'), ('RETURN', '退货')], max_length=20, verbose_name='类型'),
        ),
    ]
